spring:
  flyway:
    url: jdbc:mysql://127.0.0.1:3306/fairyhr?serverTimezone=UTC&useSSL=false
    user: admin
    password: admin
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/migration/mysql
    clean-disabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fairyhr
    username: admin
    password: admin
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl:
  mapper-locations: classpath:mappers/*.xml

---

#测试环境配置
spring:
  config:
    activate:
      on-profile: "test"
  flyway:
    url: jdbc:mysql://127.0.0.1:3306/fairyhr_test?serverTimezone=UTC&useSSL=false
    locations: classpath:db/test/migration,classpath:db/test/migration/mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fairyhr_test
    username: admin
    password: admin

logging:
  level:
    org.fairysoftw.fairyhr.mapper: debug
