spring:
  flyway:
    url: jdbc:mysql://127.0.0.1:3306/fairyhr?serverTimezone=UTC&useSSL=false
    user: root
    password: admin
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/migration/{vendor}
    clean-disabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fairyhr
    username: admin
    password: admin

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
